# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018, Olof Kraigher olof.kraigher@gmail.com

[package]
name = "vhdl_ls"
version = "0.19.0"
authors = ["Olof Kraigher <olof.kraigher@gmail.com>"]
license = "MPL-2.0"
description = "VHDL Language Server"
repository = "https://github.com/kraigher/rust_hdl"
edition = "2021"

[dependencies]
vhdl_lang = { version = "^0.19.0", path = "../vhdl_lang"}
serde_json = "*"
serde = "*"
lsp-types = "*"
fnv = "*"
log = "*"
env_logger = "*"
clap = "^2"
lsp-server = "*"

[dev-dependencies]
tempfile = "*"
pretty_assertions = "*"

[features]
default = []
packaged = ["vhdl_lang/packaged"]