name: Crates.io

on:
  push:
    branches:
    - master

jobs:
  publish:
    name: Publish
    if: github.repository == 'VHDL-LS/rust_hdl'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - uses: katyo/publish-crates@v1
      with:
          registry-token: ${{ secrets.CRATES_IO_TOKEN }}
          ignore-unpublished-changes: true