name: Docker

on:
  push:
    branches:
    - master
    tags:
    - '**'

jobs:
  publish:
    name: Publish
    if: github.repository == 'VHDL-LS/rust_hdl'
    strategy:
      matrix:
        crate:
        - vhdl_lang
        - vhdl_ls
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jerray/publish-docker-action@v1.0.3
      env:
        CRATE: ${{ matrix.crate }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kraigher/${{ matrix.crate }}
        auto_tag: true
        build_args: CRATE
  
  # A job is required when the publish job is skipped
  skip-publish:
    name: Skip publish
    if: github.repository != 'VHDL-LS/rust_hdl'
    runs-on: ubuntu-latest
    steps:
    - name: Report
      run: echo Skipped action from repository ${{ github.repository }}